ALTER TABLE servers ADD COLUMN host TEXT NOT NULL DEFAULT '';
ALTER TABLE servers ADD COLUMN winrm_user TEXT NOT NULL DEFAULT '';
ALTER TABLE servers ADD COLUMN winrm_transport TEXT NOT NULL DEFAULT 'ntlm';
ALTER TABLE servers ADD COLUMN winrm_insecure INTEGER NOT NULL DEFAULT 0;

ALTER TABLE projects ADD COLUMN iis_physical_path TEXT NOT NULL DEFAULT '';
ALTER TABLE projects ADD COLUMN iis_app_pool TEXT NOT NULL DEFAULT '';
ALTER TABLE projects ADD COLUMN iis_service TEXT NOT NULL DEFAULT '';
ALTER TABLE projects ADD COLUMN iis_build_command TEXT NOT NULL DEFAULT '';
ALTER TABLE projects ADD COLUMN iis_source_subdir TEXT NOT NULL DEFAULT '.';

ALTER TABLE deployments ADD COLUMN target_type TEXT NOT NULL DEFAULT '';
