ALTER TABLE projects ADD COLUMN source TEXT NOT NULL DEFAULT '';
ALTER TABLE projects ADD COLUMN compose_path TEXT NOT NULL DEFAULT '';
ALTER TABLE projects ADD COLUMN image TEXT NOT NULL DEFAULT '';
