// Command control-center runs the DevOps Control Center server, and provides
// small admin subcommands for hashing the admin password and managing
// encrypted credentials.
//
// Usage:
//
//	control-center [serve] [-config config.yaml]
//	control-center hash-password
//	control-center cred add <name>
//	control-center cred list
//	control-center cred get <name>
package main

import (
	"bufio"
	"context"
	"errors"
	"flag"
	"fmt"
	"io"
	"log"
	"net/http"
	"net/url"
	"os"
	"os/signal"
	"path/filepath"
	"strings"
	"time"

	"github.com/Devonlegend/winify/internal/assistant"
	"github.com/Devonlegend/winify/internal/auth"
	"github.com/Devonlegend/winify/internal/config"
	"github.com/Devonlegend/winify/internal/deployment"
	"github.com/Devonlegend/winify/internal/models"
	"github.com/Devonlegend/winify/internal/monitoring"
	"github.com/Devonlegend/winify/internal/proxy"
	"github.com/Devonlegend/winify/internal/server"
)

func main() {
	args := os.Args[1:]
	if len(args) > 0 && !strings.HasPrefix(args[0], "-") {
		switch args[0] {
		case "serve":
			runServe(args[1:])
			return
		case "hash-password":
			runHashPassword(args[1:])
			return
		case "cred":
			runCred(args[1:])
			return
		default:
			log.Fatalf("unknown command %q (want: serve, hash-password, cred)", args[0])
		}
	}
	runServe(args)
}

// ---- serve ----

func runServe(args []string) {
	fs := flag.NewFlagSet("serve", flag.ExitOnError)
	configPath := fs.String("config", defaultConfigPath(), "path to YAML config; missing file means built-in defaults")
	fs.Parse(args)

	cfg := mustConfig(*configPath)
	store, cleanup := mustStore(cfg)
	defer cleanup()

	ctx := context.Background()
	if err := store.DeleteExpiredSessions(ctx, time.Now()); err != nil {
		log.Printf("prune sessions: %v", err)
	}

	seedAdmin(ctx, store, cfg)
	seedInventory(ctx, store, cfg)

	key, err := auth.LoadMasterKey(cfg.Credentials.MasterKey, masterKeyPath(cfg))
	if err != nil {
		log.Fatalf("master key: %v", err)
	}
	credStore, err := auth.NewCredentialStore(store, key)
	if err != nil {
		log.Fatalf("credential store: %v", err)
	}

	var registrar proxy.Registrar = proxy.Noop{}
	if cfg.Proxy.Enabled {
		registrar = proxy.NewCaddy(cfg.Proxy.AdminURL, cfg.Proxy.ServerName)
	}
	if cfg.Deploy.KnownHostsFile == "" {
		log.Printf("WARNING: deploy.known_hosts_file is empty; SSH host keys will NOT be verified")
	}
	sshDial := func(ctx context.Context, srv config.Server, key string) (deployment.Runner, error) {
		return deployment.DialSSH(ctx, srv.SSHHost, srv.SSHPort, srv.SSHUser, key, cfg.Deploy.KnownHostsFile)
	}

	// Audit every remote command (deploy, rollback, monitor): target, action,
	// timestamp and deployment. Commands never contain credentials; sensitive
	// payloads are redacted by the caller before they reach here.
	auditRecorder := func(ctx context.Context, meta deployment.AuditMeta, command string, runErr error) {
		rc := models.RemoteCommand{
			ServerID:     meta.ServerID,
			ServerType:   meta.ServerType,
			Action:       meta.Action,
			DeploymentID: meta.DeploymentID,
			Command:      command,
			ExecutedAt:   time.Now(),
		}
		if runErr != nil {
			rc.Error = runErr.Error()
		}
		shown := command
		if len(shown) > 200 {
			shown = shown[:200] + "..."
		}
		log.Printf("audit: server=%s type=%s action=%s deploy=%d command=%q error=%v",
			meta.ServerID, meta.ServerType, meta.Action, meta.DeploymentID, shown, runErr)
		// Persist even if the command's context was cancelled.
		if err := store.InsertRemoteCommand(context.WithoutCancel(ctx), rc); err != nil {
			log.Printf("audit: persist: %v", err)
		}
	}

	targetFactory := deployment.NewTargetFactory(cfg, sshDial, auditRecorder)
	deployer := deployment.NewDeployer(cfg, store, credStore, registrar, targetFactory)

	// Metrics reuse the same SSH/WinRM connection code as deploys (no agent).
	collector := monitoring.NewCollector(monitoring.NewRunnerFactory(cfg, credStore, auditRecorder))
	scheduler := monitoring.NewScheduler(cfg, store, collector)
	if cfg.Monitoring.Enabled {
		scheduler.Start()
		defer scheduler.Stop()
		log.Printf("monitoring: polling every %s", scheduler.Interval())
	}

	authSvc := auth.NewService(store, cfg.Auth.CookieSecure, time.Duration(cfg.Auth.SessionTTLHours)*time.Hour)

	// Local RAG assistant: curated docs + live data, generated by Ollama.
	var assistantSvc *assistant.Service
	if cfg.Assistant.Enabled {
		assistantSvc = buildAssistant(ctx, cfg, store)
	}

	srv, err := server.New(server.Deps{
		Cfg:             cfg,
		Store:           store,
		Auth:            authSvc,
		Secrets:         credStore,
		Deployer:        deployer,
		Assistant:       assistantSvc,
		CredentialAdmin: credStore,
	})
	if err != nil {
		log.Fatalf("server: %v", err)
	}

	httpServer := &http.Server{
		Addr:              cfg.Server.Addr,
		Handler:           srv.Handler(),
		ReadHeaderTimeout: 10 * time.Second,
	}

	// ctx is cancelled on Ctrl-C / SIGINT. signal.NotifyContext is the modern
	// way to turn a signal into a context instead of a global handler.
	signalCtx, stop := signal.NotifyContext(context.Background(), os.Interrupt)
	defer stop()

	go func() {
		log.Printf("control-center listening on %s", cfg.Server.Addr)
		if err := httpServer.ListenAndServe(); err != nil && !errors.Is(err, http.ErrServerClosed) {
			log.Fatalf("listen: %v", err)
		}
	}()

	<-signalCtx.Done()
	log.Println("shutting down")

	shutdownCtx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	if err := httpServer.Shutdown(shutdownCtx); err != nil {
		log.Printf("shutdown: %v", err)
	}
}

// seedAdmin ensures the configured admin account exists. The password comes
// from CC_ADMIN_PASSWORD (hashed here) or a pre-hashed auth.admin_password_hash.
// Neither value is ever logged.
func seedAdmin(ctx context.Context, store *models.Store, cfg config.Config) {
	hash := cfg.Auth.AdminPasswordHash
	if plaintext := os.Getenv("CC_ADMIN_PASSWORD"); plaintext != "" {
		h, err := auth.HashPassword(plaintext)
		if err != nil {
			log.Fatalf("hash admin password: %v", err)
		}
		hash = h
	}
	if hash == "" {
		log.Fatal("no admin password configured: set CC_ADMIN_PASSWORD, or set auth.admin_password_hash " +
			"(generate one with: control-center hash-password)")
	}
	if err := store.UpsertUser(ctx, cfg.Auth.AdminUser, hash); err != nil {
		log.Fatalf("seed admin user: %v", err)
	}
}

// seedInventory imports servers.yaml / projects.yaml into an empty database.
// After the first run the database is the source of truth and the dashboard
// manages the inventory, so the files are not re-imported.
func seedInventory(ctx context.Context, store *models.Store, cfg config.Config) {
	if n, err := store.CountServers(ctx); err != nil {
		log.Fatalf("count servers: %v", err)
	} else if n == 0 {
		servers, err := config.LoadServers(cfg.Files.Servers)
		if err != nil {
			log.Fatalf("servers config: %v", err)
		}
		for _, srv := range servers {
			if err := store.UpsertServer(ctx, srv); err != nil {
				log.Fatalf("seed server: %v", err)
			}
		}
		log.Printf("seeded %d servers from %s", len(servers), cfg.Files.Servers)
	} else {
		log.Printf("servers table has %d rows; skipping YAML seed", n)
	}

	if n, err := store.CountProjects(ctx); err != nil {
		log.Fatalf("count projects: %v", err)
	} else if n == 0 {
		projects, err := config.LoadProjects(cfg.Files.Projects)
		if err != nil {
			log.Fatalf("projects config: %v", err)
		}
		for _, p := range projects {
			if err := store.UpsertProject(ctx, p); err != nil {
				log.Fatalf("seed project: %v", err)
			}
			// A repo URL with embedded credentials would end up in the clone
			// command and therefore in deploy logs and the audit log. Warn
			// without echoing the URL. Use target-side deploy keys instead.
			if u, err := url.Parse(p.RepoURL); err == nil && u.User != nil {
				log.Printf("WARNING: project %s repo_url embeds credentials; use target-side deploy keys instead", p.ID)
			}
		}
		log.Printf("seeded %d projects from %s", len(projects), cfg.Files.Projects)
	} else {
		log.Printf("projects table has %d rows; skipping YAML seed", n)
	}
}

// buildAssistant loads the curated docs, picks a vector store (ChromaDB with an
// in-memory fallback) and ingests the knowledge base. Ingestion is idempotent.
func buildAssistant(ctx context.Context, cfg config.Config, store *models.Store) *assistant.Service {
	docs, err := assistant.LoadDocs()
	if err != nil {
		log.Fatalf("assistant: load docs: %v", err)
	}

	fallback := assistant.NewMemoryStore()
	var primary assistant.VectorStore = fallback
	if cfg.Assistant.ChromaURL != "" {
		chroma := assistant.NewChroma(cfg.Assistant.ChromaURL, cfg.Assistant.Collection)
		pingCtx, cancel := context.WithTimeout(ctx, 3*time.Second)
		err := chroma.Ping(pingCtx)
		cancel()
		if err == nil {
			primary = chroma
			log.Printf("assistant: using ChromaDB at %s (collection %q)", cfg.Assistant.ChromaURL, cfg.Assistant.Collection)
		} else {
			log.Printf("assistant: ChromaDB unavailable (%v); using in-memory store", err)
		}
	}

	timeout := time.Duration(cfg.Assistant.TimeoutSeconds) * time.Second
	llm := assistant.NewOllama(cfg.Assistant.OllamaURL, cfg.Assistant.Model, timeout)
	svc := assistant.NewService(cfg, store, primary, fallback, llm, docs)

	ingestCtx, cancel := context.WithTimeout(ctx, 30*time.Second)
	defer cancel()
	if err := svc.Ingest(ingestCtx); err != nil {
		log.Printf("assistant: ingest: %v", err)
	}
	log.Printf("assistant: %d doc chunks ready (store=%s, model=%s)", len(docs), primary.Name(), cfg.Assistant.Model)
	return svc
}

// ---- hash-password ----

func runHashPassword(args []string) {
	fs := flag.NewFlagSet("hash-password", flag.ExitOnError)
	fs.Parse(args)

	password, err := readSecret("New admin password (input is echoed): ")
	if err != nil {
		log.Fatalf("read password: %v", err)
	}
	if password == "" {
		log.Fatal("empty password")
	}
	hash, err := auth.HashPassword(password)
	if err != nil {
		log.Fatalf("hash: %v", err)
	}
	// stdout carries only the bcrypt hash, which is safe to paste into config.
	fmt.Println(hash)
}

// ---- cred ----

func runCred(args []string) {
	fs := flag.NewFlagSet("cred", flag.ExitOnError)
	configPath := fs.String("config", defaultConfigPath(), "path to YAML config")
	fs.Parse(args)
	rest := fs.Args()

	if len(rest) == 0 {
		log.Fatal("usage: control-center cred <add|list|get> [name]")
	}
	action := rest[0]

	cfg := mustConfig(*configPath)
	store, cleanup := mustStore(cfg)
	defer cleanup()

	key, err := auth.LoadMasterKey(cfg.Credentials.MasterKey, masterKeyPath(cfg))
	if err != nil {
		log.Fatalf("master key: %v", err)
	}
	credStore, err := auth.NewCredentialStore(store, key)
	if err != nil {
		log.Fatalf("credential store: %v", err)
	}
	ctx := context.Background()

	switch action {
	case "add":
		if len(rest) < 2 {
			log.Fatal("usage: control-center cred add <name>")
		}
		name := rest[1]
		secret, err := readSecret("Secret value (input is echoed): ")
		if err != nil {
			log.Fatalf("read secret: %v", err)
		}
		if secret == "" {
			log.Fatal("empty secret, nothing stored")
		}
		if err := credStore.Put(ctx, name, secret); err != nil {
			log.Fatalf("store credential: %v", err)
		}
		// Log the name only. The secret is never printed.
		log.Printf("stored credential %q (encrypted at rest)", name)

	case "list":
		names, err := store.CredentialNames(ctx)
		if err != nil {
			log.Fatalf("list credentials: %v", err)
		}
		for _, n := range names {
			fmt.Println(n)
		}

	case "get":
		if len(rest) < 2 {
			log.Fatal("usage: control-center cred get <name>")
		}
		name := rest[1]
		secret, err := credStore.Get(ctx, name)
		if errors.Is(err, models.ErrNotFound) {
			log.Fatalf("credential %q not found", name)
		}
		if err != nil {
			log.Fatalf("read credential: %v", err)
		}
		// Deliberate: the operator asked for the plaintext. It goes to stdout,
		// never to the log, so it cannot end up in a log aggregation pipeline.
		fmt.Println(secret)

	default:
		log.Fatalf("unknown cred action %q (want: add, list, get)", action)
	}
}

// ---- shared helpers ----

func defaultConfigPath() string {
	if v := os.Getenv("CC_CONFIG"); v != "" {
		return v
	}
	return "config.yaml"
}

func mustConfig(path string) config.Config {
	cfg, err := config.Load(path)
	if err != nil {
		log.Fatalf("config: %v", err)
	}
	return cfg
}

func mustStore(cfg config.Config) (*models.Store, func()) {
	if dir := filepath.Dir(cfg.Database.Path); dir != "." {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			log.Fatalf("create data dir %s: %v", dir, err)
		}
	}
	db, err := models.Open(cfg.Database.Path)
	if err != nil {
		log.Fatalf("database: %v", err)
	}
	if err := models.Migrate(db); err != nil {
		db.Close()
		log.Fatalf("migrate: %v", err)
	}
	return models.NewStore(db), func() { db.Close() }
}

// masterKeyPath keeps the generated key beside the database in the data dir.
func masterKeyPath(cfg config.Config) string {
	return filepath.Join(filepath.Dir(cfg.Database.Path), "master.key")
}

// readSecret reads a secret from stdin. When stdin is piped or redirected it
// reads the whole stream, so multi-line secrets such as SSH private keys work
// with `control-center cred add name < key`. Interactively it reads one line.
func readSecret(prompt string) (string, error) {
	if info, err := os.Stdin.Stat(); err == nil && info.Mode()&os.ModeCharDevice == 0 {
		data, err := io.ReadAll(os.Stdin)
		if err != nil {
			return "", err
		}
		return strings.TrimRight(string(data), "\r\n"), nil
	}

	fmt.Fprint(os.Stderr, prompt)
	line, err := bufio.NewReader(os.Stdin).ReadString('\n')
	if err != nil && !errors.Is(err, io.EOF) {
		return "", err
	}
	return strings.TrimRight(line, "\r\n"), nil
}
